[package]
name = "archiver"
version = "0.1.0"
authors = ["Richo Healey <richo@psych0tik.net>"]

[features]
"web" = [
  "rocket",
  "rocket_contrib",
  "diesel",
  "bcrypt",
  "rand",
  "oauth2",
  "dotenv"
]

[dependencies]
rocket = { git = "https://github.com/SergioBenitez/Rocket", optional = true , features=["tls"]}
rocket_contrib = { git = "https://github.com/SergioBenitez/Rocket", optional = true, default_features = false, features = ["handlebars_templates", "json", "serve"] }
diesel = { version = "1.3.3", features = ["postgres", "r2d2", "serde_json", "chrono"], optional = true}
bcrypt = { version = "0.2", optional = true }
rand = { version = "0.5.5", optional = true }
oauth2 = { version = "2.0.0-alpha.2", optional = true }
dotenv = { version ="0.13", optional = true }

toml = "0.4.7"
clap = "2.32.0"
serde = "1.0.79"
serde_derive = "1.0.79"
serde_json = "1.0.31"
failure = "0.1.2"
lazy_static = "1.1.0"
libusb = "0.3.0"
ptp = { git = "https://github.com/richo/rust-ptp" }
chrono = { version = "0.4.6", features = ["serde"] }
regex = "1.0.5"
reqwest = "0.9.2"
log = "0.4.5"
pretty_env_logger = "0.2.4"
hashing-copy = "0.2"
tempfile = "3.0.4"
walkdir = "2.2.5"
hex = "0.3.2"
digest = "0.7.6"
sha2 = "0.7.1"
handlebars = "1.0.4"
sendgrid = { git = "https://github.com/gsquire/sendgrid-rs" }
url = "1.7"
tus = "0.2.0"
failure_derive = "0.1.2"
filetime = "0.2.1"
rpassword = "2.0.0"

[[bin]]
name = "server"
path = "src/bin/server.rs"
required-features = ["web"]

[[bin]]
name = "runner"
path = "src/bin/runner.rs"
