[package]
name = "archiver"
version = "0.1.0"
authors = ["Richo Healey <richo@psych0tik.net>"]
edition = "2018"

[features]
"web" = [
  "rocket",
  "rocket_contrib",
  "diesel",
  "bcrypt",
  "rand",
  "oauth2",
  "dotenv"
]

[dependencies]
rocket = { version = "0.4.0", optional = true, features = ["tls"] }
rocket_contrib = { version = "0.4.0", optional = true, default_features = false, features = ["handlebars_templates", "json", "serve"] }
diesel = { version = "1.4.0", features = ["postgres", "r2d2", "serde_json", "chrono"], optional = true }
bcrypt = { version = "0.2.2", optional = true }
rand = { version = "0.6.4", optional = true }
oauth2 = { version = "2.0.0-alpha.2", optional = true }
dotenv = { version = "0.13.0", optional = true }

toml = "0.4.10"
clap = "2.32.0"
serde = { version = "1.0.85", features = ["derive"] }
serde_derive = "1.0.85"
serde_json = "1.0.36"
failure = "0.1.5"
lazy_static = "1.2.0"
libusb = "0.3.0"
ptp = { git = "https://github.com/richo/rust-ptp" }
chrono = { version = "0.4.6", features = ["serde"] }
regex = "1.1.0"
reqwest = "0.9.8"
log = "0.4.6"
pretty_env_logger = "0.3.0"
hashing-copy = "0.3.0"
tempfile = "3.0.5"
walkdir = "2.2.7"
hex = "0.3.2"
digest = "0.8.0"
sha2 = "0.8.0"
handlebars = "1.1.0"
sendgrid = { git = "https://github.com/gsquire/sendgrid-rs" }
url = "1.7.2"
tus = "0.2.0"
failure_derive = "0.1.5"
filetime = "0.2.4"
rpassword = "2.1.0"
dirs = "1.0.4"
time = "0.1.42"

[[bin]]
name = "server"
path = "src/bin/server.rs"
required-features = ["web"]

[[bin]]
name = "runner"
path = "src/bin/runner.rs"
